repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
    -   id: isort
        args: [
            --lines-after-imports=2,
            --force-single-line-imports,
            --multi-line=3,
            --line-length=100,
            --force-alphabetical-sort-within-sections,
            --profile=black
        ]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3.12
        args: [--line-length=100]
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.12.0]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
        language_version: python3.12
        args: [--all]
