name: Pull request to master

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    uses: sherbie/spot-risk-assessment/.github/workflows/job-qa.yml@master
    with:
      do_test: true
      do_sonar_scan: true
      do_check_sonar_quality_gate: true
    secrets: inherit
  